### PR TITLE
Update participants.yml

### PR DESCRIPTION
**Pull request by the-dr-lazy**

### CODE REVIEW

**Comment by s-soroosh** [comment]
Thanks @thebrodmann, 
I'll merge it once your code is in place

**Comment by the-dr-lazy** [comment]
You can find the `prime` in [thebrodmann/soallpeach](https://github.com/thebrodmann/soallpeach/tree/master) on master branch.

**Comment by s-soroosh** [comment]
Excellent٫ thanks

**Comment by s-soroosh** [comment]
@thebrodmann The image build job has been failed. 
Here you can find the reason:
https://soallpeach-api-soroosh.fandogh.cloud/scores/86

**Comment by the-dr-lazy** [comment]
Does this mean the disk is full?

Screen Shot 2020-04-06 at 2 00 39 AM

**Comment by the-dr-lazy** [comment]
BTW, I changed Dockerfile to use cabal.

**Comment by s-soroosh** [comment]
@thebrodmann, Yes it sounds like the storage is not enough to build the image. 
the github runner has 14GB disk though.  
Let's see how cabal performs. apparently the image build is relatively slow for such program. 
On my machine it took ~6minutes to build.

**Comment by the-dr-lazy** [comment]
Yes, cabal doesn't use Nix cache tho it should build all dependencies.
> On my machine it took ~6minutes to build.

Does the build phase count in the benchmark? I can make Dockerfile multi-stage if it's needed.

**Comment by s-soroosh** [comment]
> Yes, cabal should build all dependencies. cabal don't use Nix cache.
> 
> > On my machine it took ~6minutes to build.
> 
> Does the build phase count in the benchmark? I can make Dockerfile multi-stage if it's needed.

No it doesn't, just slow down the test pipeline. 
Here you go: 
https://soallpeach-api-soroosh.fandogh.cloud/

**Pull request merged**
